version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/sphinx_extensions.txt